server:
  port: 8082
spring:
  application:
    name: service-feign

# eurekaÅäÖÃ
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

# Æô¶¯feignÖĞ¶ÏÂ·Æ÷
feign:
  hystrix:
    enabled: true