server
  port: 8888
spring
  application
    name: config-server


spring
  cloud
    config
    server
      git
        uri: https://github.com/forezp/SpringcloudConfig/ #配置git仓库地址
        searchPaths: respo  #配置仓库路径
        label: master #配置仓库的分支
        username: chenyumin #访问git仓库的用户名
        password: 123 #访问git仓库的用户密码

