server:
  port: 8085

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master #对应git的分支。如果配置中心使用的是本地存储，则该参数无用
      profile: dev  #对应{profile}部分
      uri: https://github.com/forezp/SpringcloudConfig/ #配置git仓库地址